### ISSUE TITLE
Fatal error when initializing a new static website

### ISSUE THREAD

**Issue by CyberSecutor** [ZeroConfig/StaticWebsite#1]
I am getting this error when i run
$ composer create-project zero-config/static-website

for the first time.

symfony/polyfill-mbstring suggests installing ext-mbstring (For best performance)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/polyfill-intl-icu suggests installing ext-intl (For best performance)
composer/composer suggests installing ext-zip (Enabling the zip extension allows you to unzip archives)
zero-config/preacher suggests installing zero-config/preacher-plugin-commonmark (Use CommonMark as source reader.)
Writing lock file
Generating autoload files
> rm -f README.md
> test -d .git || git init
Initialized empty Git repository in /home/remko/git/static-website/.git/
> test -h .git/hooks/post-commit || test -d .git/hooks && ln -s ../../vendor/bin/preach .git/hooks/post-commit
> composer init
> composer require --dev zero-config/preacher:^2.1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating zero-config/preacher (3.0.0 => 2.2.0): Downloading (100%)         
Writing lock file
Generating autoload files
> git add .; git commit -am 'Finished installation.'
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
Stack trace:
#0 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(263): Symfony\Component\Config\Util\XmlUtils::loadFile('/home/remko/git...', Array)
#1 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/home/remko/git...')
#2 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(72): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
#3 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(59): Symfony\Bundle\FrameworkBundle\DependencyInjection\Framewor in /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52
[master (root-commit) 6663cec] Finished installation.
 16 files changed, 7105 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 composer.json
 create mode 100644 css/bootstrap-theme.css
 create mode 100644 css/bootstrap-theme.css.map
 create mode 100644 css/bootstrap-theme.min.css
 create mode 100644 css/bootstrap.css
 create mode 100644 css/bootstrap.css.map
 create mode 100644 css/bootstrap.min.css
 create mode 100644 css/main.css
 create mode 100644 default.html.twig
 create mode 100644 favicon.ico
 create mode 100644 fonts/glyphicons-halflings-regular.eot
 create mode 100644 fonts/glyphicons-halflings-regular.svg
 create mode 100644 fonts/glyphicons-halflings-regular.ttf
 create mode 100644 fonts/glyphicons-halflings-regular.woff
 create mode 100644 index.md
> vendor/bin/preach -f
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
Stack trace:
#0 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(263): Symfony\Component\Config\Util\XmlUtils::loadFile('/home/remko/git...', Array)
#1 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/home/remko/git...')
#2 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(72): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
#3 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(59): Symfony\Bundle\FrameworkBundle\DependencyInjection\Framewor in /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52
Script vendor/bin/preach -f handling the post-create-project-cmd event returned with an error

                                                                                                                                  
  [RuntimeException]                                                                                                              
  Error Output: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/remko/git/static-website/vendor/symfony  
  /symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52                                                                      
  Stack trace:                                                                                                                    
  #0 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(26  
  3): Symfony\Component\Config\Util\XmlUtils::loadFile('/home/remko/git...', Array)                                               
  #1 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41  
  ): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/home/remko/git...')                             
  #2 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExten  
  sion.php(72): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')                                       
  #3 /home/remko/git/static-website/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConf  
  igurationPass.php(59): Symfony\Bundle\FrameworkBundle\DependencyInjection\Framewor in /home/remko/git/static-website/vendor/sy  
  mfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52                                                         
                                                                                                                                  

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by CyberSecutor** [comment]
Nevermind, it needs php-xml installed.
